//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public int IDTK { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public string TypeAcc { get; set; }
        public string NAME { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public string EMAIL { get; set; }
        public string CHUCVU { get; set; }
        public byte[] PhotoAC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
    }
}
