//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.MENUDETAILs = new HashSet<MENUDETAIL>();
        }
    
        public int IDBILL { get; set; }
        public Nullable<int> IDTK { get; set; }
        public int IDKH { get; set; }
        public Nullable<int> IDSanh { get; set; }
        public Nullable<int> IDPARTY { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> Time { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int DISCOUNT { get; set; }
        public double DATCOC { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string STATUS { get; set; }
        public string INCUR { get; set; }
        public double INCURCOST { get; set; }
        public Nullable<System.DateTime> PayDay { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual BILL BILL1 { get; set; }
        public virtual BILL BILL2 { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PARTY PARTY { get; set; }
        public virtual SANH SANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENUDETAIL> MENUDETAILs { get; set; }
    }
}
