//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.MENUDETAILs = new HashSet<MENUDETAIL>();
        }
    
        public int IDFood { get; set; }
        public int IDFoodCategory { get; set; }
        public string NameFood { get; set; }
        public double PriceFood { get; set; }
        public byte[] PhotoFood { get; set; }
        public string Material { get; set; }
    
        public virtual FOODCATEGORY FOODCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENUDETAIL> MENUDETAILs { get; set; }
    }
}
