//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CSDL : DbContext
    {
        public CSDL()
            : base("name=CSDL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<FOOD> FOODs { get; set; }
        public virtual DbSet<FOODCATEGORY> FOODCATEGORies { get; set; }
        public virtual DbSet<MENUDETAIL> MENUDETAILs { get; set; }
        public virtual DbSet<PARTY> PARTies { get; set; }
        public virtual DbSet<SANH> SANHs { get; set; }
    
        public virtual int AddMenuDetail(Nullable<int> iDFood, Nullable<int> iDBILL, Nullable<int> sLFood, Nullable<double> priceFood)
        {
            var iDFoodParameter = iDFood.HasValue ?
                new ObjectParameter("IDFood", iDFood) :
                new ObjectParameter("IDFood", typeof(int));
    
            var iDBILLParameter = iDBILL.HasValue ?
                new ObjectParameter("IDBILL", iDBILL) :
                new ObjectParameter("IDBILL", typeof(int));
    
            var sLFoodParameter = sLFood.HasValue ?
                new ObjectParameter("SLFood", sLFood) :
                new ObjectParameter("SLFood", typeof(int));
    
            var priceFoodParameter = priceFood.HasValue ?
                new ObjectParameter("PriceFood", priceFood) :
                new ObjectParameter("PriceFood", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddMenuDetail", iDFoodParameter, iDBILLParameter, sLFoodParameter, priceFoodParameter);
        }
    
        public virtual int AddParty(string namePT, Nullable<double> pricePT, byte[] photoParty)
        {
            var namePTParameter = namePT != null ?
                new ObjectParameter("NamePT", namePT) :
                new ObjectParameter("NamePT", typeof(string));
    
            var pricePTParameter = pricePT.HasValue ?
                new ObjectParameter("PricePT", pricePT) :
                new ObjectParameter("PricePT", typeof(double));
    
            var photoPartyParameter = photoParty != null ?
                new ObjectParameter("PhotoParty", photoParty) :
                new ObjectParameter("PhotoParty", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddParty", namePTParameter, pricePTParameter, photoPartyParameter);
        }
    
        public virtual int AddSanh(string nameSanh, Nullable<int> sIZE, Nullable<double> priceSanh, byte[] photoSanh)
        {
            var nameSanhParameter = nameSanh != null ?
                new ObjectParameter("NameSanh", nameSanh) :
                new ObjectParameter("NameSanh", typeof(string));
    
            var sIZEParameter = sIZE.HasValue ?
                new ObjectParameter("SIZE", sIZE) :
                new ObjectParameter("SIZE", typeof(int));
    
            var priceSanhParameter = priceSanh.HasValue ?
                new ObjectParameter("PriceSanh", priceSanh) :
                new ObjectParameter("PriceSanh", typeof(double));
    
            var photoSanhParameter = photoSanh != null ?
                new ObjectParameter("PhotoSanh", photoSanh) :
                new ObjectParameter("PhotoSanh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSanh", nameSanhParameter, sIZEParameter, priceSanhParameter, photoSanhParameter);
        }
    
        public virtual int DelBill(Nullable<int> iDBILL)
        {
            var iDBILLParameter = iDBILL.HasValue ?
                new ObjectParameter("IDBILL", iDBILL) :
                new ObjectParameter("IDBILL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DelBill", iDBILLParameter);
        }
    
        public virtual int DeleSanh(Nullable<int> iDSanh)
        {
            var iDSanhParameter = iDSanh.HasValue ?
                new ObjectParameter("IDSanh", iDSanh) :
                new ObjectParameter("IDSanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleSanh", iDSanhParameter);
        }
    
        public virtual int DelMenuDetail(Nullable<int> iDFood, Nullable<int> iDBILL)
        {
            var iDFoodParameter = iDFood.HasValue ?
                new ObjectParameter("IDFood", iDFood) :
                new ObjectParameter("IDFood", typeof(int));
    
            var iDBILLParameter = iDBILL.HasValue ?
                new ObjectParameter("IDBILL", iDBILL) :
                new ObjectParameter("IDBILL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DelMenuDetail", iDFoodParameter, iDBILLParameter);
        }
    
        public virtual int DelPT(Nullable<int> iDPARTY)
        {
            var iDPARTYParameter = iDPARTY.HasValue ?
                new ObjectParameter("IDPARTY", iDPARTY) :
                new ObjectParameter("IDPARTY", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DelPT", iDPARTYParameter);
        }
    
        public virtual int EditBill(Nullable<int> iDBILL, Nullable<int> iDSanh, Nullable<int> time, Nullable<int> quantity, Nullable<double> tOTAL)
        {
            var iDBILLParameter = iDBILL.HasValue ?
                new ObjectParameter("IDBILL", iDBILL) :
                new ObjectParameter("IDBILL", typeof(int));
    
            var iDSanhParameter = iDSanh.HasValue ?
                new ObjectParameter("IDSanh", iDSanh) :
                new ObjectParameter("IDSanh", typeof(int));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("Time", time) :
                new ObjectParameter("Time", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var tOTALParameter = tOTAL.HasValue ?
                new ObjectParameter("TOTAL", tOTAL) :
                new ObjectParameter("TOTAL", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditBill", iDBILLParameter, iDSanhParameter, timeParameter, quantityParameter, tOTALParameter);
        }
    
        public virtual int EditMenuDetail(Nullable<int> iDFood, Nullable<int> iDBILL, Nullable<int> sLFood, Nullable<double> priceFood)
        {
            var iDFoodParameter = iDFood.HasValue ?
                new ObjectParameter("IDFood", iDFood) :
                new ObjectParameter("IDFood", typeof(int));
    
            var iDBILLParameter = iDBILL.HasValue ?
                new ObjectParameter("IDBILL", iDBILL) :
                new ObjectParameter("IDBILL", typeof(int));
    
            var sLFoodParameter = sLFood.HasValue ?
                new ObjectParameter("SLFood", sLFood) :
                new ObjectParameter("SLFood", typeof(int));
    
            var priceFoodParameter = priceFood.HasValue ?
                new ObjectParameter("PriceFood", priceFood) :
                new ObjectParameter("PriceFood", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditMenuDetail", iDFoodParameter, iDBILLParameter, sLFoodParameter, priceFoodParameter);
        }
    
        public virtual int EditParty(Nullable<int> iDPARTY, string namePT, Nullable<double> pricePT, byte[] photoParty)
        {
            var iDPARTYParameter = iDPARTY.HasValue ?
                new ObjectParameter("IDPARTY", iDPARTY) :
                new ObjectParameter("IDPARTY", typeof(int));
    
            var namePTParameter = namePT != null ?
                new ObjectParameter("NamePT", namePT) :
                new ObjectParameter("NamePT", typeof(string));
    
            var pricePTParameter = pricePT.HasValue ?
                new ObjectParameter("PricePT", pricePT) :
                new ObjectParameter("PricePT", typeof(double));
    
            var photoPartyParameter = photoParty != null ?
                new ObjectParameter("PhotoParty", photoParty) :
                new ObjectParameter("PhotoParty", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditParty", iDPARTYParameter, namePTParameter, pricePTParameter, photoPartyParameter);
        }
    
        public virtual int EditSanh(Nullable<int> iDSanh, string nameSanh, Nullable<int> sIZE, Nullable<double> priceSanh, byte[] photoSanh)
        {
            var iDSanhParameter = iDSanh.HasValue ?
                new ObjectParameter("IDSanh", iDSanh) :
                new ObjectParameter("IDSanh", typeof(int));
    
            var nameSanhParameter = nameSanh != null ?
                new ObjectParameter("NameSanh", nameSanh) :
                new ObjectParameter("NameSanh", typeof(string));
    
            var sIZEParameter = sIZE.HasValue ?
                new ObjectParameter("SIZE", sIZE) :
                new ObjectParameter("SIZE", typeof(int));
    
            var priceSanhParameter = priceSanh.HasValue ?
                new ObjectParameter("PriceSanh", priceSanh) :
                new ObjectParameter("PriceSanh", typeof(double));
    
            var photoSanhParameter = photoSanh != null ?
                new ObjectParameter("PhotoSanh", photoSanh) :
                new ObjectParameter("PhotoSanh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditSanh", iDSanhParameter, nameSanhParameter, sIZEParameter, priceSanhParameter, photoSanhParameter);
        }
    
        public virtual ObjectResult<ShowBll_Result> ShowBll(Nullable<System.DateTime> bookingDay)
        {
            var bookingDayParameter = bookingDay.HasValue ?
                new ObjectParameter("BookingDay", bookingDay) :
                new ObjectParameter("BookingDay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowBll_Result>("ShowBll", bookingDayParameter);
        }
    
        public virtual ObjectResult<ShowMenu_Result> ShowMenu(Nullable<int> iDBill)
        {
            var iDBillParameter = iDBill.HasValue ?
                new ObjectParameter("IDBill", iDBill) :
                new ObjectParameter("IDBill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowMenu_Result>("ShowMenu", iDBillParameter);
        }
    
        public virtual ObjectResult<ShowMenu1_Result> ShowMenu1(Nullable<int> iDBill)
        {
            var iDBillParameter = iDBill.HasValue ?
                new ObjectParameter("IDBill", iDBill) :
                new ObjectParameter("IDBill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowMenu1_Result>("ShowMenu1", iDBillParameter);
        }
    }
}
